_extends: specialist-github-config

repository:
  name: flags-cookie
  description: A utility library for interacting with flag override cookies.
  topics: specialist-titles
  default_branch: main
  private: false

branches:
  - name: main
    protection:
      # Require CI status checks to pass
      required_status_checks:
        strict: false
        contexts:
          - test
